# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'configdialog.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(454, 546)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setContentsMargins(12, 12, 12, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.camera_label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.camera_label.setFont(font)
        self.camera_label.setObjectName("camera_label")
        self.verticalLayout_2.addWidget(self.camera_label)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.cam_label_1 = QtWidgets.QLabel(Dialog)
        self.cam_label_1.setObjectName("cam_label_1")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.cam_label_1)
        self.camera_combo_1 = QtWidgets.QComboBox(Dialog)
        self.camera_combo_1.setEnabled(True)
        self.camera_combo_1.setObjectName("camera_combo_1")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.camera_combo_1)
        self.cam_label_2 = QtWidgets.QLabel(Dialog)
        self.cam_label_2.setObjectName("cam_label_2")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.cam_label_2)
        self.camera_combo_2 = QtWidgets.QComboBox(Dialog)
        self.camera_combo_2.setObjectName("camera_combo_2")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.camera_combo_2)
        self.cam_label_3 = QtWidgets.QLabel(Dialog)
        self.cam_label_3.setObjectName("cam_label_3")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.cam_label_3)
        self.camera_combo_3 = QtWidgets.QComboBox(Dialog)
        self.camera_combo_3.setObjectName("camera_combo_3")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.camera_combo_3)
        self.cam_label_4 = QtWidgets.QLabel(Dialog)
        self.cam_label_4.setObjectName("cam_label_4")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.cam_label_4)
        self.camera_combo_4 = QtWidgets.QComboBox(Dialog)
        self.camera_combo_4.setObjectName("camera_combo_4")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.camera_combo_4)
        self.verticalLayout_2.addLayout(self.formLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.camera_reset_button = QtWidgets.QPushButton(Dialog)
        self.camera_reset_button.setObjectName("camera_reset_button")
        self.horizontalLayout.addWidget(self.camera_reset_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.ftp_label_2 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ftp_label_2.setFont(font)
        self.ftp_label_2.setObjectName("ftp_label_2")
        self.verticalLayout_2.addWidget(self.ftp_label_2)
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_5.setObjectName("formLayout_5")
        self.username_label_2 = QtWidgets.QLabel(Dialog)
        self.username_label_2.setAutoFillBackground(False)
        self.username_label_2.setObjectName("username_label_2")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.username_label_2)
        self.password_label_2 = QtWidgets.QLabel(Dialog)
        self.password_label_2.setObjectName("password_label_2")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.password_label_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.turntable_period = QtWidgets.QLineEdit(Dialog)
        self.turntable_period.setMinimumSize(QtCore.QSize(100, 0))
        self.turntable_period.setMaximumSize(QtCore.QSize(200, 16777215))
        self.turntable_period.setObjectName("turntable_period")
        self.horizontalLayout_2.addWidget(self.turntable_period)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.formLayout_5.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.photos_per_scan = QtWidgets.QLineEdit(Dialog)
        self.photos_per_scan.setMinimumSize(QtCore.QSize(100, 0))
        self.photos_per_scan.setMaximumSize(QtCore.QSize(200, 16777215))
        self.photos_per_scan.setObjectName("photos_per_scan")
        self.horizontalLayout_3.addWidget(self.photos_per_scan)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.formLayout_5.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.formLayout_5)
        self.line_3 = QtWidgets.QFrame(Dialog)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        self.ftp_label = QtWidgets.QLabel(Dialog)
        self.ftp_label.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ftp_label.setFont(font)
        self.ftp_label.setObjectName("ftp_label")
        self.verticalLayout_2.addWidget(self.ftp_label)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.host_labal = QtWidgets.QLabel(Dialog)
        self.host_labal.setObjectName("host_labal")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.host_labal)
        self.host = QtWidgets.QLineEdit(Dialog)
        self.host.setEnabled(False)
        self.host.setObjectName("host")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.host)
        self.username_label = QtWidgets.QLabel(Dialog)
        self.username_label.setObjectName("username_label")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.username_label)
        self.username = QtWidgets.QLineEdit(Dialog)
        self.username.setEnabled(True)
        self.username.setMaximumSize(QtCore.QSize(200, 16777215))
        self.username.setObjectName("username")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.username)
        self.password_label = QtWidgets.QLabel(Dialog)
        self.password_label.setObjectName("password_label")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.password_label)
        self.password = QtWidgets.QLineEdit(Dialog)
        self.password.setEnabled(True)
        self.password.setMaximumSize(QtCore.QSize(200, 16777215))
        self.password.setInputMask("")
        self.password.setText("")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setClearButtonEnabled(False)
        self.password.setObjectName("password")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.password)
        self.verticalLayout_2.addLayout(self.formLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.unlock_ftp_button = QtWidgets.QPushButton(Dialog)
        self.unlock_ftp_button.setObjectName("unlock_ftp_button")
        self.horizontalLayout_4.addWidget(self.unlock_ftp_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Initial Setup"))
        self.camera_label.setText(_translate("Dialog", "Cameras"))
        self.label.setText(_translate("Dialog", "Select Camera positions below"))
        self.cam_label_1.setText(_translate("Dialog", "Camera 1: "))
        self.cam_label_2.setText(_translate("Dialog", "Camera 2: "))
        self.cam_label_3.setText(_translate("Dialog", "Camera 3: "))
        self.cam_label_4.setText(_translate("Dialog", "Camera 4: "))
        self.camera_reset_button.setText(_translate("Dialog", "Reset Camera Assignments"))
        self.ftp_label_2.setText(_translate("Dialog", "Turntable Settings"))
        self.username_label_2.setText(_translate("Dialog", "Turntable Period: "))
        self.password_label_2.setText(_translate("Dialog", "Photos Per Rotation: "))
        self.label_2.setText(_translate("Dialog", "seconds"))
        self.label_3.setText(_translate("Dialog", "count"))
        self.ftp_label.setText(_translate("Dialog", "FTP Settings"))
        self.host_labal.setText(_translate("Dialog", "Host: "))
        self.host.setText(_translate("Dialog", "FTPPartner.wayfair.com"))
        self.username_label.setText(_translate("Dialog", "Username: "))
        self.password_label.setText(_translate("Dialog", "Password: "))
        self.unlock_ftp_button.setText(_translate("Dialog", "Unlock FTP Settings"))

