# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'initdialog.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(417, 379)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setContentsMargins(12, 12, 12, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.camera_label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.camera_label.setFont(font)
        self.camera_label.setObjectName("camera_label")
        self.verticalLayout_2.addWidget(self.camera_label)
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.camera_model_label = QtWidgets.QLabel(Dialog)
        self.camera_model_label.setObjectName("camera_model_label")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.camera_model_label)
        self.camera_model = QtWidgets.QLineEdit(Dialog)
        self.camera_model.setObjectName("camera_model")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.camera_model)
        self.camera_count_label = QtWidgets.QLabel(Dialog)
        self.camera_count_label.setObjectName("camera_count_label")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.camera_count_label)
        self.camera_count = QtWidgets.QSpinBox(Dialog)
        self.camera_count.setMaximumSize(QtCore.QSize(40, 16777215))
        self.camera_count.setMaximum(9)
        self.camera_count.setProperty("value", 4)
        self.camera_count.setObjectName("camera_count")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.camera_count)
        self.verticalLayout_2.addLayout(self.formLayout_4)
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.ftp_label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ftp_label.setFont(font)
        self.ftp_label.setObjectName("ftp_label")
        self.verticalLayout_2.addWidget(self.ftp_label)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.host_labal = QtWidgets.QLabel(Dialog)
        self.host_labal.setObjectName("host_labal")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.host_labal)
        self.host = QtWidgets.QLineEdit(Dialog)
        self.host.setObjectName("host")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.host)
        self.username_label = QtWidgets.QLabel(Dialog)
        self.username_label.setObjectName("username_label")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.username_label)
        self.username = QtWidgets.QLineEdit(Dialog)
        self.username.setMaximumSize(QtCore.QSize(200, 16777215))
        self.username.setObjectName("username")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.username)
        self.password_label = QtWidgets.QLabel(Dialog)
        self.password_label.setObjectName("password_label")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.password_label)
        self.password = QtWidgets.QLineEdit(Dialog)
        self.password.setMaximumSize(QtCore.QSize(200, 16777215))
        self.password.setObjectName("password")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.password)
        self.verticalLayout_2.addLayout(self.formLayout_3)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Initial Setup"))
        self.camera_label.setText(_translate("Dialog", "Cameras"))
        self.camera_model_label.setText(_translate("Dialog", "Model"))
        self.camera_model.setText(_translate("Dialog", "Canon Something"))
        self.camera_count_label.setText(_translate("Dialog", "Number"))
        self.ftp_label.setText(_translate("Dialog", "FTP Settings"))
        self.host_labal.setText(_translate("Dialog", "Host"))
        self.host.setText(_translate("Dialog", "FTPPartner.wayfair.com"))
        self.username_label.setText(_translate("Dialog", "Username"))
        self.password_label.setText(_translate("Dialog", "Password"))

