# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(934, 796)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout_7.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.scan_name_label = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scan_name_label.sizePolicy().hasHeightForWidth())
        self.scan_name_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.scan_name_label.setFont(font)
        self.scan_name_label.setObjectName("scan_name_label")
        self.horizontalLayout.addWidget(self.scan_name_label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.scan_progress_container = QtWidgets.QWidget(self.centralWidget)
        self.scan_progress_container.setMinimumSize(QtCore.QSize(20, 40))
        self.scan_progress_container.setObjectName("scan_progress_container")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.scan_progress_container)
        self.horizontalLayout_9.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.scan_progress = QtWidgets.QProgressBar(self.scan_progress_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scan_progress.sizePolicy().hasHeightForWidth())
        self.scan_progress.setSizePolicy(sizePolicy)
        self.scan_progress.setProperty("value", 24)
        self.scan_progress.setObjectName("scan_progress")
        self.horizontalLayout_9.addWidget(self.scan_progress)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem)
        self.current_scan_label = QtWidgets.QLabel(self.scan_progress_container)
        self.current_scan_label.setObjectName("current_scan_label")
        self.horizontalLayout_9.addWidget(self.current_scan_label)
        self.label_8 = QtWidgets.QLabel(self.scan_progress_container)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_9.addWidget(self.label_8)
        self.total_scan_label = QtWidgets.QLabel(self.scan_progress_container)
        self.total_scan_label.setObjectName("total_scan_label")
        self.horizontalLayout_9.addWidget(self.total_scan_label)
        self.verticalLayout.addWidget(self.scan_progress_container)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideLeft)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.thumb_tab = QtWidgets.QWidget()
        self.thumb_tab.setObjectName("thumb_tab")
        self.gridLayout = QtWidgets.QGridLayout(self.thumb_tab)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.thumbnail_1 = QtWidgets.QLabel(self.thumb_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.thumbnail_1.sizePolicy().hasHeightForWidth())
        self.thumbnail_1.setSizePolicy(sizePolicy)
        self.thumbnail_1.setMinimumSize(QtCore.QSize(256, 256))
        self.thumbnail_1.setMaximumSize(QtCore.QSize(1024, 1024))
        self.thumbnail_1.setAutoFillBackground(False)
        self.thumbnail_1.setStyleSheet("QLabel { background-color : #555}")
        self.thumbnail_1.setFrameShape(QtWidgets.QFrame.Panel)
        self.thumbnail_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.thumbnail_1.setLineWidth(2)
        self.thumbnail_1.setMidLineWidth(2)
        self.thumbnail_1.setAlignment(QtCore.Qt.AlignCenter)
        self.thumbnail_1.setWordWrap(False)
        self.thumbnail_1.setObjectName("thumbnail_1")
        self.gridLayout.addWidget(self.thumbnail_1, 0, 0, 1, 1)
        self.thumbnail_2 = QtWidgets.QLabel(self.thumb_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.thumbnail_2.sizePolicy().hasHeightForWidth())
        self.thumbnail_2.setSizePolicy(sizePolicy)
        self.thumbnail_2.setMinimumSize(QtCore.QSize(256, 256))
        self.thumbnail_2.setMaximumSize(QtCore.QSize(1024, 1024))
        self.thumbnail_2.setAutoFillBackground(False)
        self.thumbnail_2.setStyleSheet("QLabel { background-color : #555}")
        self.thumbnail_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.thumbnail_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.thumbnail_2.setLineWidth(2)
        self.thumbnail_2.setAlignment(QtCore.Qt.AlignCenter)
        self.thumbnail_2.setWordWrap(False)
        self.thumbnail_2.setObjectName("thumbnail_2")
        self.gridLayout.addWidget(self.thumbnail_2, 0, 1, 1, 1)
        self.thumbnail_3 = QtWidgets.QLabel(self.thumb_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.thumbnail_3.sizePolicy().hasHeightForWidth())
        self.thumbnail_3.setSizePolicy(sizePolicy)
        self.thumbnail_3.setMinimumSize(QtCore.QSize(256, 256))
        self.thumbnail_3.setMaximumSize(QtCore.QSize(1024, 1024))
        self.thumbnail_3.setAutoFillBackground(False)
        self.thumbnail_3.setStyleSheet("QLabel { background-color : #555}")
        self.thumbnail_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.thumbnail_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.thumbnail_3.setLineWidth(2)
        self.thumbnail_3.setAlignment(QtCore.Qt.AlignCenter)
        self.thumbnail_3.setWordWrap(False)
        self.thumbnail_3.setObjectName("thumbnail_3")
        self.gridLayout.addWidget(self.thumbnail_3, 1, 0, 1, 1)
        self.thumbnail_4 = QtWidgets.QLabel(self.thumb_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.thumbnail_4.sizePolicy().hasHeightForWidth())
        self.thumbnail_4.setSizePolicy(sizePolicy)
        self.thumbnail_4.setMinimumSize(QtCore.QSize(256, 256))
        self.thumbnail_4.setMaximumSize(QtCore.QSize(1024, 1024))
        self.thumbnail_4.setAutoFillBackground(False)
        self.thumbnail_4.setStyleSheet("QLabel { background-color : #555}")
        self.thumbnail_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.thumbnail_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.thumbnail_4.setLineWidth(2)
        self.thumbnail_4.setAlignment(QtCore.Qt.AlignCenter)
        self.thumbnail_4.setWordWrap(False)
        self.thumbnail_4.setObjectName("thumbnail_4")
        self.gridLayout.addWidget(self.thumbnail_4, 1, 1, 1, 1)
        self.tabWidget.addTab(self.thumb_tab, "")
        self.settings_tab = QtWidgets.QWidget()
        self.settings_tab.setObjectName("settings_tab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.settings_tab)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setSpacing(6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frame = QtWidgets.QFrame(self.settings_tab)
        font = QtGui.QFont()
        font.setKerning(False)
        self.frame.setFont(font)
        self.frame.setAutoFillBackground(False)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 10)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setContentsMargins(10, -1, -1, -1)
        self.formLayout.setHorizontalSpacing(6)
        self.formLayout.setVerticalSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.label_7 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.aperture_4 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.aperture_4.setFont(font)
        self.aperture_4.setObjectName("aperture_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.aperture_4)
        self.label_10 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.shutter_4 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.shutter_4.setFont(font)
        self.shutter_4.setObjectName("shutter_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.shutter_4)
        self.label_12 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.ISO_4 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ISO_4.setFont(font)
        self.ISO_4.setObjectName("ISO_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ISO_4)
        self.label_14 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.shoot_mode_4 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.shoot_mode_4.setFont(font)
        self.shoot_mode_4.setObjectName("shoot_mode_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.shoot_mode_4)
        self.label_16 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.focus_mode_4 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.focus_mode_4.setFont(font)
        self.focus_mode_4.setObjectName("focus_mode_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.focus_mode_4)
        self.verticalLayout_3.addLayout(self.formLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setContentsMargins(10, -1, 10, -1)
        self.horizontalLayout_24.setSpacing(6)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem3)
        self.label_98 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_98.setFont(font)
        self.label_98.setObjectName("label_98")
        self.horizontalLayout_24.addWidget(self.label_98)
        self.lens_4 = QtWidgets.QLabel(self.frame)
        self.lens_4.setMaximumSize(QtCore.QSize(190, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lens_4.setFont(font)
        self.lens_4.setScaledContents(True)
        self.lens_4.setObjectName("lens_4")
        self.horizontalLayout_24.addWidget(self.lens_4)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setContentsMargins(5, -1, 5, -1)
        self.horizontalLayout_20.setSpacing(6)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_48 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_48.setFont(font)
        self.label_48.setObjectName("label_48")
        self.horizontalLayout_20.addWidget(self.label_48)
        self.counter_4 = QtWidgets.QLabel(self.frame)
        self.counter_4.setObjectName("counter_4")
        self.horizontalLayout_20.addWidget(self.counter_4)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem5)
        self.label_50 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_50.setFont(font)
        self.label_50.setObjectName("label_50")
        self.horizontalLayout_20.addWidget(self.label_50)
        self.available_4 = QtWidgets.QLabel(self.frame)
        self.available_4.setObjectName("available_4")
        self.horizontalLayout_20.addWidget(self.available_4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_20)
        self.gridLayout_6.addWidget(self.frame, 1, 1, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.settings_tab)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 10)
        self.verticalLayout_15.setSpacing(6)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem6)
        self.formLayout_9 = QtWidgets.QFormLayout()
        self.formLayout_9.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_9.setContentsMargins(10, -1, -1, -1)
        self.formLayout_9.setHorizontalSpacing(6)
        self.formLayout_9.setVerticalSpacing(10)
        self.formLayout_9.setObjectName("formLayout_9")
        self.label_93 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_93.setFont(font)
        self.label_93.setObjectName("label_93")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_93)
        self.aperture_2 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.aperture_2.setFont(font)
        self.aperture_2.setObjectName("aperture_2")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.aperture_2)
        self.label_95 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_95.setFont(font)
        self.label_95.setObjectName("label_95")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_95)
        self.shutter_2 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.shutter_2.setFont(font)
        self.shutter_2.setObjectName("shutter_2")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.shutter_2)
        self.label_97 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_97.setFont(font)
        self.label_97.setObjectName("label_97")
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_97)
        self.ISO_2 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ISO_2.setFont(font)
        self.ISO_2.setObjectName("ISO_2")
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ISO_2)
        self.label_99 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_99.setFont(font)
        self.label_99.setObjectName("label_99")
        self.formLayout_9.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_99)
        self.shoot_mode_2 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.shoot_mode_2.setFont(font)
        self.shoot_mode_2.setObjectName("shoot_mode_2")
        self.formLayout_9.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.shoot_mode_2)
        self.label_101 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_101.setFont(font)
        self.label_101.setObjectName("label_101")
        self.formLayout_9.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_101)
        self.focus_mode_2 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.focus_mode_2.setFont(font)
        self.focus_mode_2.setObjectName("focus_mode_2")
        self.formLayout_9.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.focus_mode_2)
        self.verticalLayout_15.addLayout(self.formLayout_9)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem7)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setContentsMargins(10, -1, 10, -1)
        self.horizontalLayout_22.setSpacing(6)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem8)
        self.label_94 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_94.setFont(font)
        self.label_94.setObjectName("label_94")
        self.horizontalLayout_22.addWidget(self.label_94)
        self.lens_2 = QtWidgets.QLabel(self.frame_6)
        self.lens_2.setMaximumSize(QtCore.QSize(190, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lens_2.setFont(font)
        self.lens_2.setScaledContents(True)
        self.lens_2.setObjectName("lens_2")
        self.horizontalLayout_22.addWidget(self.lens_2)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem9)
        self.verticalLayout_15.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setContentsMargins(5, -1, 5, -1)
        self.horizontalLayout_18.setSpacing(6)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_17 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_18.addWidget(self.label_17)
        self.counter_2 = QtWidgets.QLabel(self.frame_6)
        self.counter_2.setObjectName("counter_2")
        self.horizontalLayout_18.addWidget(self.counter_2)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem10)
        self.label_13 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_18.addWidget(self.label_13)
        self.available_2 = QtWidgets.QLabel(self.frame_6)
        self.available_2.setObjectName("available_2")
        self.horizontalLayout_18.addWidget(self.available_2)
        self.verticalLayout_15.addLayout(self.horizontalLayout_18)
        self.gridLayout_6.addWidget(self.frame_6, 0, 1, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.settings_tab)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 10)
        self.verticalLayout_10.setSpacing(6)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem11)
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_4.setContentsMargins(10, -1, -1, -1)
        self.formLayout_4.setHorizontalSpacing(6)
        self.formLayout_4.setVerticalSpacing(10)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_43 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_43)
        self.aperture_3 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.aperture_3.setFont(font)
        self.aperture_3.setObjectName("aperture_3")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.aperture_3)
        self.label_45 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_45)
        self.shutter_3 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.shutter_3.setFont(font)
        self.shutter_3.setObjectName("shutter_3")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.shutter_3)
        self.label_47 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_47.setFont(font)
        self.label_47.setObjectName("label_47")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_47)
        self.ISO_3 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ISO_3.setFont(font)
        self.ISO_3.setObjectName("ISO_3")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ISO_3)
        self.label_49 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_49.setFont(font)
        self.label_49.setObjectName("label_49")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_49)
        self.shoot_mode_3 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.shoot_mode_3.setFont(font)
        self.shoot_mode_3.setObjectName("shoot_mode_3")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.shoot_mode_3)
        self.label_51 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_51.setFont(font)
        self.label_51.setObjectName("label_51")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_51)
        self.focus_mode_3 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.focus_mode_3.setFont(font)
        self.focus_mode_3.setObjectName("focus_mode_3")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.focus_mode_3)
        self.verticalLayout_10.addLayout(self.formLayout_4)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem12)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setContentsMargins(10, -1, 10, -1)
        self.horizontalLayout_23.setSpacing(6)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem13)
        self.label_96 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_96.setFont(font)
        self.label_96.setObjectName("label_96")
        self.horizontalLayout_23.addWidget(self.label_96)
        self.lens_3 = QtWidgets.QLabel(self.frame_4)
        self.lens_3.setMaximumSize(QtCore.QSize(190, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lens_3.setFont(font)
        self.lens_3.setScaledContents(True)
        self.lens_3.setObjectName("lens_3")
        self.horizontalLayout_23.addWidget(self.lens_3)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem14)
        self.verticalLayout_10.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setContentsMargins(5, -1, 5, -1)
        self.horizontalLayout_19.setSpacing(6)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_44 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.horizontalLayout_19.addWidget(self.label_44)
        self.counter_3 = QtWidgets.QLabel(self.frame_4)
        self.counter_3.setObjectName("counter_3")
        self.horizontalLayout_19.addWidget(self.counter_3)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem15)
        self.label_46 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_46.setFont(font)
        self.label_46.setObjectName("label_46")
        self.horizontalLayout_19.addWidget(self.label_46)
        self.available_3 = QtWidgets.QLabel(self.frame_4)
        self.available_3.setObjectName("available_3")
        self.horizontalLayout_19.addWidget(self.available_3)
        self.verticalLayout_10.addLayout(self.horizontalLayout_19)
        self.gridLayout_6.addWidget(self.frame_4, 1, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.settings_tab)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 10)
        self.verticalLayout_14.setSpacing(6)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem16)
        self.formLayout_8 = QtWidgets.QFormLayout()
        self.formLayout_8.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_8.setContentsMargins(10, -1, -1, -1)
        self.formLayout_8.setHorizontalSpacing(6)
        self.formLayout_8.setVerticalSpacing(10)
        self.formLayout_8.setObjectName("formLayout_8")
        self.label_83 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_83.setFont(font)
        self.label_83.setObjectName("label_83")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_83)
        self.aperture_1 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.aperture_1.setFont(font)
        self.aperture_1.setObjectName("aperture_1")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.aperture_1)
        self.label_85 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_85.setFont(font)
        self.label_85.setObjectName("label_85")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_85)
        self.shutter_1 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.shutter_1.setFont(font)
        self.shutter_1.setObjectName("shutter_1")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.shutter_1)
        self.label_87 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_87.setFont(font)
        self.label_87.setObjectName("label_87")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_87)
        self.ISO_1 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ISO_1.setFont(font)
        self.ISO_1.setObjectName("ISO_1")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ISO_1)
        self.label_89 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_89.setFont(font)
        self.label_89.setObjectName("label_89")
        self.formLayout_8.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_89)
        self.shoot_mode_1 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.shoot_mode_1.setFont(font)
        self.shoot_mode_1.setObjectName("shoot_mode_1")
        self.formLayout_8.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.shoot_mode_1)
        self.label_91 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_91.setFont(font)
        self.label_91.setObjectName("label_91")
        self.formLayout_8.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_91)
        self.focus_mode_1 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.focus_mode_1.setFont(font)
        self.focus_mode_1.setObjectName("focus_mode_1")
        self.formLayout_8.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.focus_mode_1)
        self.verticalLayout_14.addLayout(self.formLayout_8)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem17)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setContentsMargins(10, -1, 10, -1)
        self.horizontalLayout_21.setSpacing(6)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem18)
        self.label_92 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_92.setFont(font)
        self.label_92.setObjectName("label_92")
        self.horizontalLayout_21.addWidget(self.label_92)
        self.lens_1 = QtWidgets.QLabel(self.frame_5)
        self.lens_1.setMaximumSize(QtCore.QSize(190, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lens_1.setFont(font)
        self.lens_1.setScaledContents(True)
        self.lens_1.setObjectName("lens_1")
        self.horizontalLayout_21.addWidget(self.lens_1)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem19)
        self.verticalLayout_14.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setContentsMargins(5, -1, 5, -1)
        self.horizontalLayout_17.setSpacing(6)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_15 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_17.addWidget(self.label_15)
        self.counter_1 = QtWidgets.QLabel(self.frame_5)
        self.counter_1.setObjectName("counter_1")
        self.horizontalLayout_17.addWidget(self.counter_1)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem20)
        self.label_11 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_17.addWidget(self.label_11)
        self.available_1 = QtWidgets.QLabel(self.frame_5)
        self.available_1.setObjectName("available_1")
        self.horizontalLayout_17.addWidget(self.available_1)
        self.verticalLayout_14.addLayout(self.horizontalLayout_17)
        self.gridLayout_6.addWidget(self.frame_5, 0, 0, 1, 1)
        self.tabWidget.addTab(self.settings_tab, "")
        self.horizontalLayout_2.addWidget(self.tabWidget)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.camera_count_group = QtWidgets.QGroupBox(self.centralWidget)
        self.camera_count_group.setObjectName("camera_count_group")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.camera_count_group)
        self.verticalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.camera_count_group)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.image_count_1 = QtWidgets.QLCDNumber(self.camera_count_group)
        self.image_count_1.setStyleSheet("")
        self.image_count_1.setObjectName("image_count_1")
        self.horizontalLayout_3.addWidget(self.image_count_1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.camera_count_group)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.image_count_2 = QtWidgets.QLCDNumber(self.camera_count_group)
        self.image_count_2.setStyleSheet("")
        self.image_count_2.setObjectName("image_count_2")
        self.horizontalLayout_4.addWidget(self.image_count_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.camera_count_group)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.image_count_3 = QtWidgets.QLCDNumber(self.camera_count_group)
        self.image_count_3.setStyleSheet("")
        self.image_count_3.setObjectName("image_count_3")
        self.horizontalLayout_5.addWidget(self.image_count_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.camera_count_group)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.image_count_4 = QtWidgets.QLCDNumber(self.camera_count_group)
        self.image_count_4.setStyleSheet("")
        self.image_count_4.setObjectName("image_count_4")
        self.horizontalLayout_6.addWidget(self.image_count_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.verticalLayout_4.addWidget(self.camera_count_group)
        self.initialize_button = QtWidgets.QPushButton(self.centralWidget)
        self.initialize_button.setObjectName("initialize_button")
        self.verticalLayout_4.addWidget(self.initialize_button)
        spacerItem21 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem21)
        self.label_6 = QtWidgets.QLabel(self.centralWidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.textEdit = QtWidgets.QTextEdit(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setMaximumSize(QtCore.QSize(200, 600))
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_4.addWidget(self.textEdit)
        self.new_scan_button = QtWidgets.QPushButton(self.centralWidget)
        self.new_scan_button.setObjectName("new_scan_button")
        self.verticalLayout_4.addWidget(self.new_scan_button)
        spacerItem22 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem22)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem23)
        self.ftp_button = QtWidgets.QPushButton(self.centralWidget)
        self.ftp_button.setObjectName("ftp_button")
        self.horizontalLayout_8.addWidget(self.ftp_button)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 934, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menuBar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menuBar)
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionConfig = QtWidgets.QAction(MainWindow)
        self.actionConfig.setObjectName("actionConfig")
        self.menuFile.addAction(self.actionClose)
        self.menuEdit.addAction(self.actionConfig)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Wayfair Next - WayScan"))
        self.label_5.setText(_translate("MainWindow", "Now Scanning: "))
        self.scan_name_label.setText(_translate("MainWindow", "N/A"))
        self.current_scan_label.setText(_translate("MainWindow", "0"))
        self.label_8.setText(_translate("MainWindow", "of"))
        self.total_scan_label.setText(_translate("MainWindow", "20"))
        self.thumbnail_1.setText(_translate("MainWindow", "Camera 1 Preview"))
        self.thumbnail_2.setText(_translate("MainWindow", "Camera 2 Preview"))
        self.thumbnail_3.setText(_translate("MainWindow", "Camera 3 Preview"))
        self.thumbnail_4.setText(_translate("MainWindow", "Camera 4 Preview"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.thumb_tab), _translate("MainWindow", "Camera Thumbnails"))
        self.label_7.setText(_translate("MainWindow", "Aperture: "))
        self.aperture_4.setText(_translate("MainWindow", "TextLabel"))
        self.label_10.setText(_translate("MainWindow", "Shutter Speed: "))
        self.shutter_4.setText(_translate("MainWindow", "TextLabel"))
        self.label_12.setText(_translate("MainWindow", "ISO: "))
        self.ISO_4.setText(_translate("MainWindow", "TextLabel"))
        self.label_14.setText(_translate("MainWindow", "Shoot Mode: "))
        self.shoot_mode_4.setText(_translate("MainWindow", "Manual"))
        self.label_16.setText(_translate("MainWindow", "Focus Mode: "))
        self.focus_mode_4.setText(_translate("MainWindow", "Manual"))
        self.label_98.setText(_translate("MainWindow", "Lens:"))
        self.lens_4.setText(_translate("MainWindow", "N/A"))
        self.label_48.setText(_translate("MainWindow", "Shutter Count:"))
        self.counter_4.setText(_translate("MainWindow", "TextLabel"))
        self.label_50.setText(_translate("MainWindow", "Remaining:"))
        self.available_4.setText(_translate("MainWindow", "TextLabel"))
        self.label_93.setText(_translate("MainWindow", "Aperture: "))
        self.aperture_2.setText(_translate("MainWindow", "TextLabel"))
        self.label_95.setText(_translate("MainWindow", "Shutter Speed: "))
        self.shutter_2.setText(_translate("MainWindow", "TextLabel"))
        self.label_97.setText(_translate("MainWindow", "ISO: "))
        self.ISO_2.setText(_translate("MainWindow", "TextLabel"))
        self.label_99.setText(_translate("MainWindow", "Shoot Mode: "))
        self.shoot_mode_2.setText(_translate("MainWindow", "Manual"))
        self.label_101.setText(_translate("MainWindow", "Focus Mode: "))
        self.focus_mode_2.setText(_translate("MainWindow", "Manual"))
        self.label_94.setText(_translate("MainWindow", "Lens:"))
        self.lens_2.setText(_translate("MainWindow", "N/A"))
        self.label_17.setText(_translate("MainWindow", "Shutter Count:"))
        self.counter_2.setText(_translate("MainWindow", "TextLabel"))
        self.label_13.setText(_translate("MainWindow", "Remaining:"))
        self.available_2.setText(_translate("MainWindow", "TextLabel"))
        self.label_43.setText(_translate("MainWindow", "Aperture: "))
        self.aperture_3.setText(_translate("MainWindow", "TextLabel"))
        self.label_45.setText(_translate("MainWindow", "Shutter Speed: "))
        self.shutter_3.setText(_translate("MainWindow", "TextLabel"))
        self.label_47.setText(_translate("MainWindow", "ISO: "))
        self.ISO_3.setText(_translate("MainWindow", "TextLabel"))
        self.label_49.setText(_translate("MainWindow", "Shoot Mode: "))
        self.shoot_mode_3.setText(_translate("MainWindow", "Manual"))
        self.label_51.setText(_translate("MainWindow", "Focus Mode: "))
        self.focus_mode_3.setText(_translate("MainWindow", "Manual"))
        self.label_96.setText(_translate("MainWindow", "Lens:"))
        self.lens_3.setText(_translate("MainWindow", "N/A"))
        self.label_44.setText(_translate("MainWindow", "Shutter Count:"))
        self.counter_3.setText(_translate("MainWindow", "TextLabel"))
        self.label_46.setText(_translate("MainWindow", "Remaining:"))
        self.available_3.setText(_translate("MainWindow", "TextLabel"))
        self.label_83.setText(_translate("MainWindow", "Aperture: "))
        self.aperture_1.setText(_translate("MainWindow", "TextLabel"))
        self.label_85.setText(_translate("MainWindow", "Shutter Speed: "))
        self.shutter_1.setText(_translate("MainWindow", "TextLabel"))
        self.label_87.setText(_translate("MainWindow", "ISO: "))
        self.ISO_1.setText(_translate("MainWindow", "TextLabel"))
        self.label_89.setText(_translate("MainWindow", "Shoot Mode: "))
        self.shoot_mode_1.setText(_translate("MainWindow", "Manual"))
        self.label_91.setText(_translate("MainWindow", "Focus Mode: "))
        self.focus_mode_1.setText(_translate("MainWindow", "Manual"))
        self.label_92.setText(_translate("MainWindow", "Lens:"))
        self.lens_1.setText(_translate("MainWindow", "N/A"))
        self.label_15.setText(_translate("MainWindow", "Shutter Count:"))
        self.counter_1.setText(_translate("MainWindow", "TextLabel"))
        self.label_11.setText(_translate("MainWindow", "Remaining:"))
        self.available_1.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settings_tab), _translate("MainWindow", "Camera Settings"))
        self.camera_count_group.setTitle(_translate("MainWindow", "Photos Taken"))
        self.label.setText(_translate("MainWindow", "Camera 1:"))
        self.label_2.setText(_translate("MainWindow", "Camera 2:"))
        self.label_3.setText(_translate("MainWindow", "Camera 3:"))
        self.label_4.setText(_translate("MainWindow", "Camera 4:"))
        self.initialize_button.setText(_translate("MainWindow", "Initialization Shot"))
        self.label_6.setText(_translate("MainWindow", "Log"))
        self.new_scan_button.setText(_translate("MainWindow", "Start Scan"))
        self.ftp_button.setText(_translate("MainWindow", "Transfer Data"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionConfig.setText(_translate("MainWindow", "Config"))

