# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(503, 447)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.thumbnail_1 = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.thumbnail_1.sizePolicy().hasHeightForWidth())
        self.thumbnail_1.setSizePolicy(sizePolicy)
        self.thumbnail_1.setMinimumSize(QtCore.QSize(128, 128))
        self.thumbnail_1.setMaximumSize(QtCore.QSize(128, 128))
        self.thumbnail_1.setWordWrap(True)
        self.thumbnail_1.setObjectName("thumbnail_1")
        self.gridLayout.addWidget(self.thumbnail_1, 0, 0, 1, 1)
        self.thumbnail_3 = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.thumbnail_3.sizePolicy().hasHeightForWidth())
        self.thumbnail_3.setSizePolicy(sizePolicy)
        self.thumbnail_3.setMinimumSize(QtCore.QSize(128, 128))
        self.thumbnail_3.setMaximumSize(QtCore.QSize(128, 128))
        self.thumbnail_3.setWordWrap(True)
        self.thumbnail_3.setObjectName("thumbnail_3")
        self.gridLayout.addWidget(self.thumbnail_3, 1, 0, 1, 1)
        self.thumbnail_2 = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.thumbnail_2.sizePolicy().hasHeightForWidth())
        self.thumbnail_2.setSizePolicy(sizePolicy)
        self.thumbnail_2.setMinimumSize(QtCore.QSize(128, 128))
        self.thumbnail_2.setMaximumSize(QtCore.QSize(128, 128))
        self.thumbnail_2.setWordWrap(True)
        self.thumbnail_2.setObjectName("thumbnail_2")
        self.gridLayout.addWidget(self.thumbnail_2, 0, 1, 1, 1)
        self.thumbnail_4 = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.thumbnail_4.sizePolicy().hasHeightForWidth())
        self.thumbnail_4.setSizePolicy(sizePolicy)
        self.thumbnail_4.setMinimumSize(QtCore.QSize(128, 128))
        self.thumbnail_4.setObjectName("thumbnail_4")
        self.gridLayout.addWidget(self.thumbnail_4, 1, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.camera_count_group = QtWidgets.QGroupBox(self.centralWidget)
        self.camera_count_group.setObjectName("camera_count_group")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.camera_count_group)
        self.verticalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.camera_count_group)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.image_count_1 = QtWidgets.QLCDNumber(self.camera_count_group)
        self.image_count_1.setStyleSheet("QLCDNumber{\n"
"  color: rgb(255, 89, 242);    \n"
"  background-color: rgb(0, 85, 0);\n"
"}")
        self.image_count_1.setObjectName("image_count_1")
        self.horizontalLayout_3.addWidget(self.image_count_1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.camera_count_group)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.image_count_2 = QtWidgets.QLCDNumber(self.camera_count_group)
        self.image_count_2.setStyleSheet("QLCDNumber{\n"
"  color: rgb(255, 89, 242);    \n"
"  background-color: rgb(0, 85, 0);\n"
"}")
        self.image_count_2.setObjectName("image_count_2")
        self.horizontalLayout_4.addWidget(self.image_count_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.camera_count_group)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.image_count_3 = QtWidgets.QLCDNumber(self.camera_count_group)
        self.image_count_3.setStyleSheet("QLCDNumber{\n"
"  color: rgb(255, 89, 242);    \n"
"  background-color: rgb(0, 85, 0);\n"
"}")
        self.image_count_3.setObjectName("image_count_3")
        self.horizontalLayout_5.addWidget(self.image_count_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.camera_count_group)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.image_count_4 = QtWidgets.QLCDNumber(self.camera_count_group)
        self.image_count_4.setStyleSheet("QLCDNumber{\n"
"  color: rgb(255, 89, 242);    \n"
"  background-color: rgb(0, 85, 0);\n"
"}")
        self.image_count_4.setObjectName("image_count_4")
        self.horizontalLayout_6.addWidget(self.image_count_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.verticalLayout_4.addWidget(self.camera_count_group)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.initialize_button = QtWidgets.QPushButton(self.centralWidget)
        self.initialize_button.setObjectName("initialize_button")
        self.verticalLayout_4.addWidget(self.initialize_button)
        self.start_button = QtWidgets.QPushButton(self.centralWidget)
        self.start_button.setObjectName("start_button")
        self.verticalLayout_4.addWidget(self.start_button)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Wayfair Next - QuickCapture"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Name of Scan"))
        self.pushButton.setText(_translate("MainWindow", "Set Name"))
        self.thumbnail_1.setText(_translate("MainWindow", "Camera 1 Preview"))
        self.thumbnail_3.setText(_translate("MainWindow", "Camera 3 Preview"))
        self.thumbnail_2.setText(_translate("MainWindow", "Camera 2 Preview"))
        self.thumbnail_4.setText(_translate("MainWindow", "Camera 4 Preview"))
        self.camera_count_group.setTitle(_translate("MainWindow", "Photos Taken"))
        self.label.setText(_translate("MainWindow", "Camera 1:"))
        self.label_2.setText(_translate("MainWindow", "Camera 2:"))
        self.label_3.setText(_translate("MainWindow", "Camera 3:"))
        self.label_4.setText(_translate("MainWindow", "Camera 4:"))
        self.initialize_button.setText(_translate("MainWindow", "Initialization Shot"))
        self.start_button.setText(_translate("MainWindow", "Start Scan"))

