# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ftpdialog.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FTPDialog(object):
    def setupUi(self, FTPDialog):
        FTPDialog.setObjectName("FTPDialog")
        FTPDialog.resize(561, 617)
        self.verticalLayout = QtWidgets.QVBoxLayout(FTPDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_9 = QtWidgets.QLabel(FTPDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_3.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(FTPDialog)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_3.addWidget(self.label_10)
        self.line_3 = QtWidgets.QFrame(FTPDialog)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_3.addWidget(self.line_3)
        self.label_7 = QtWidgets.QLabel(FTPDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.host_label = QtWidgets.QLabel(FTPDialog)
        self.host_label.setObjectName("host_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.host_label)
        self.host = QtWidgets.QLineEdit(FTPDialog)
        self.host.setObjectName("host")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.host)
        self.username_label = QtWidgets.QLabel(FTPDialog)
        self.username_label.setObjectName("username_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.username_label)
        self.username = QtWidgets.QLineEdit(FTPDialog)
        self.username.setObjectName("username")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.username)
        self.verticalLayout_3.addLayout(self.formLayout)
        self.horizontalLayout_6.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.logo = QtWidgets.QLabel(FTPDialog)
        self.logo.setMinimumSize(QtCore.QSize(128, 128))
        self.logo.setMaximumSize(QtCore.QSize(128, 128))
        self.logo.setObjectName("logo")
        self.verticalLayout_4.addWidget(self.logo)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout_6.addLayout(self.verticalLayout_4)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.line = QtWidgets.QFrame(FTPDialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.progress_label = QtWidgets.QLabel(FTPDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.progress_label.setFont(font)
        self.progress_label.setObjectName("progress_label")
        self.verticalLayout.addWidget(self.progress_label)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(FTPDialog)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.progressBar = QtWidgets.QProgressBar(FTPDialog)
        self.progressBar.setMinimumSize(QtCore.QSize(0, 0))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_2.addWidget(self.progressBar)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(FTPDialog)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.progressBar_3 = QtWidgets.QProgressBar(FTPDialog)
        self.progressBar_3.setProperty("value", 24)
        self.progressBar_3.setObjectName("progressBar_3")
        self.horizontalLayout_4.addWidget(self.progressBar_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(FTPDialog)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.progressBar_4 = QtWidgets.QProgressBar(FTPDialog)
        self.progressBar_4.setProperty("value", 24)
        self.progressBar_4.setObjectName("progressBar_4")
        self.horizontalLayout_5.addWidget(self.progressBar_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(FTPDialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.progressBar_2 = QtWidgets.QProgressBar(FTPDialog)
        self.progressBar_2.setProperty("value", 24)
        self.progressBar_2.setObjectName("progressBar_2")
        self.horizontalLayout_3.addWidget(self.progressBar_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.line_2 = QtWidgets.QFrame(FTPDialog)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.status_label = QtWidgets.QLabel(FTPDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.status_label.setFont(font)
        self.status_label.setObjectName("status_label")
        self.verticalLayout.addWidget(self.status_label)
        self.status_log = QtWidgets.QTextEdit(FTPDialog)
        self.status_log.setObjectName("status_log")
        self.verticalLayout.addWidget(self.status_log)
        self.buttonBox = QtWidgets.QDialogButtonBox(FTPDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(FTPDialog)
        self.buttonBox.accepted.connect(FTPDialog.accept)
        self.buttonBox.rejected.connect(FTPDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(FTPDialog)

    def retranslateUi(self, FTPDialog):
        _translate = QtCore.QCoreApplication.translate
        FTPDialog.setWindowTitle(_translate("FTPDialog", "Dialog"))
        self.label_9.setText(_translate("FTPDialog", "Summary"))
        self.label_10.setText(_translate("FTPDialog", "Transfer XXX Files to Wayfair Next Scanning Service?"))
        self.label_7.setText(_translate("FTPDialog", "FTP Details"))
        self.host_label.setText(_translate("FTPDialog", "FTP Host: "))
        self.username_label.setText(_translate("FTPDialog", "Username: "))
        self.logo.setText(_translate("FTPDialog", "TextLabel"))
        self.progress_label.setText(_translate("FTPDialog", "Transfer Progress"))
        self.label.setText(_translate("FTPDialog", "Camera 1: "))
        self.label_3.setText(_translate("FTPDialog", "Camera 2: "))
        self.label_4.setText(_translate("FTPDialog", "Camera 3: "))
        self.label_2.setText(_translate("FTPDialog", "Camera 4: "))
        self.status_label.setText(_translate("FTPDialog", "Status"))

