# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newscandialog.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_NewScanDialog(object):
    def setupUi(self, NewScanDialog):
        NewScanDialog.setObjectName("NewScanDialog")
        NewScanDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        NewScanDialog.resize(440, 362)
        self.verticalLayout = QtWidgets.QVBoxLayout(NewScanDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(NewScanDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.subject_type = QtWidgets.QComboBox(NewScanDialog)
        self.subject_type.setObjectName("subject_type")
        self.subject_type.addItem("")
        self.subject_type.addItem("")
        self.verticalLayout.addWidget(self.subject_type)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(NewScanDialog)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.scan_name_input = QtWidgets.QLineEdit(NewScanDialog)
        self.scan_name_input.setObjectName("scan_name_input")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.scan_name_input)
        self.scan_type_label = QtWidgets.QLabel(NewScanDialog)
        self.scan_type_label.setObjectName("scan_type_label")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.scan_type_label)
        self.scan_type_input = QtWidgets.QComboBox(NewScanDialog)
        self.scan_type_input.setObjectName("scan_type_input")
        self.scan_type_input.addItem("")
        self.scan_type_input.addItem("")
        self.scan_type_input.addItem("")
        self.scan_type_input.addItem("")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.scan_type_input)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.line = QtWidgets.QFrame(NewScanDialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.label_2 = QtWidgets.QLabel(NewScanDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.scan_notes_input = QtWidgets.QPlainTextEdit(NewScanDialog)
        self.scan_notes_input.setObjectName("scan_notes_input")
        self.verticalLayout.addWidget(self.scan_notes_input)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.cancel_button = QtWidgets.QPushButton(NewScanDialog)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout_2.addWidget(self.cancel_button)
        self.start_scan_button = QtWidgets.QPushButton(NewScanDialog)
        self.start_scan_button.setAutoDefault(True)
        self.start_scan_button.setDefault(True)
        self.start_scan_button.setObjectName("start_scan_button")
        self.horizontalLayout_2.addWidget(self.start_scan_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(NewScanDialog)
        QtCore.QMetaObject.connectSlotsByName(NewScanDialog)
        NewScanDialog.setTabOrder(self.start_scan_button, self.subject_type)
        NewScanDialog.setTabOrder(self.subject_type, self.cancel_button)

    def retranslateUi(self, NewScanDialog):
        _translate = QtCore.QCoreApplication.translate
        NewScanDialog.setWindowTitle(_translate("NewScanDialog", "Set Scanning Details"))
        self.label_3.setText(_translate("NewScanDialog", "What would you like to do?"))
        self.subject_type.setCurrentText(_translate("NewScanDialog", "Scan A New Subject"))
        self.subject_type.setItemText(0, _translate("NewScanDialog", "Scan A New Subject"))
        self.subject_type.setItemText(1, _translate("NewScanDialog", "Scan An Additional Part (multipart subject)"))
        self.label.setText(_translate("NewScanDialog", "Name of Scan: "))
        self.scan_name_input.setPlaceholderText(_translate("NewScanDialog", "Enter Name (RefProd/Mfg Part No.)"))
        self.scan_type_label.setText(_translate("NewScanDialog", "Scan Type: "))
        self.scan_type_input.setItemText(0, _translate("NewScanDialog", "SKU"))
        self.scan_type_input.setItemText(1, _translate("NewScanDialog", "Prop"))
        self.scan_type_input.setItemText(2, _translate("NewScanDialog", "Experiment"))
        self.scan_type_input.setItemText(3, _translate("NewScanDialog", "Other"))
        self.label_2.setText(_translate("NewScanDialog", "Notes"))
        self.cancel_button.setText(_translate("NewScanDialog", "Cancel"))
        self.start_scan_button.setText(_translate("NewScanDialog", "Start Scan"))

